### ISSUE TITLE
Counting Cronjobs Seems Incorrect

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/AutomaticActionUX#2]
I'm not sure why but the php count for the `task.cronjob.daily` isn't shown correctly.

Can anybody help with checking the counter?

https://github.com/aljawaid/AutomaticActionUX/blob/2e3f8720f4934eac01c61bbeb217f6af4e49186b/Template/action/index.php#L19

**Comment by aljawaid** [comment]
@creecros could you kindly shed any light on this?

**Comment by creecros** [comment]
I'll take a look tomorrow.

**Comment by aljawaid** [comment]
thanks for the update

**Comment by creecros** [comment]
remove the + 1
 `$systemTriggerCounter = $this->text->contains($action['event_name'], 'task.cronjob.daily') ; `

**Comment by creecros** [comment]
Also, that said: https://github.com/aljawaid/AutomaticActionUX/blob/a5ff5e7ba85646f4263e2156fccb4ddf45e361ed/Template/action/index.php#L22

This line is an issue if there are no actions. Since `$systemTriggerCounter` is undefined if it does not go through the `for each` loop.

**Comment by creecros** [comment]
And you also need to remove the +1 here:
https://github.com/aljawaid/AutomaticActionUX/blob/a5ff5e7ba85646f4263e2156fccb4ddf45e361ed/Template/project_header/actions.php#L18

**Comment by aljawaid** [comment]
@creecros ok perfect thanks so much for that, I will make the changes shortly.

I added you to my glancer plugin... hoping you could help with the comment id search function pretty pretty please

**Comment by aljawaid** [comment]
> remove the + 1 `$systemTriggerCounter = $this->text->contains($action['event_name'], 'task.cronjob.daily') ; `
> 
> and it works just fine now. ![image](https://user-images.githubusercontent.com/26339368/198910725-c970ec74-2ab3-4dc5-8fa0-9b921dac8a79.png)

I applied your changes, still doesnt work on my side.... i got 2 background jobs and it counts total as one... the final count is correct, just the user/cron split seems weird

![image](https://user-images.githubusercontent.com/10233708/198913704-0e0eb949-2968-4397-ad74-770a011ea02e.png)

**Comment by aljawaid** [comment]
Reopened as it still doesnt count the cronjobs right, but you can see the changes i made now in the commit

**Comment by creecros** [comment]
hmm, worked perfect for me, ill take another look sometime this week. too late for me now.

**Comment by aljawaid** [comment]
> hmm, worked perfect for me, ill take another look sometime this week. too late for me now.

yeh cool, thanks alot...

**Comment by creecros** [comment]
So ya, Test project 1 is fine, but Test project 2 is off...
https://www.nachostudio.ml/dashboard

**Comment by creecros** [comment]
oh...duh.

$this->text->contiains is a boolean.

**Comment by aljawaid** [comment]
> oh...duh.
> 
> $this->text->contains is a boolean.

ok i missed that from the countless snippets, howtos and tutorials i go through lol.... but thanks for this fix also!
